fix: debug PAT

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,6 +11,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check if secret exists
+        run: |
+          if [ -z "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" ]; then
+            echo "::error::GH_PERSONAL_ACCESS_TOKEN is not set"
+            exit 1
+          else
+            echo "GH_PERSONAL_ACCESS_TOKEN is available"
+          fi
+
       - name: Checkout
         uses: actions/checkout@v4
 
